### ISSUE TITLE
计算共轭分子三重态，报错

### ISSUE THREAD

**Issue by FreemanTheMaverick** [yangwangmadrid/EzReson#3]
汪老师：

您好。听闻EzReson可以处理开壳层波函数了，我就拿了个共轭分子三重态试一试，结果报错如下。

```
(base) freeman@freeman-ThinkPad-S5-S540:~/g09/MyMol/erotate$ ezreson E1t_nbo_lmo.in # 算局域轨道
Traceback (most recent call last):
  File "/home/freeman/EzReson_v3.0_release/ezreson.py", line 1475, in <module>
    runJob_LMO( p.basename )
  File "/home/freeman/EzReson_v3.0_release/ezreson.py", line 842, in runJob_LMO
    CAONAO = readNBOMat( basename + '.33', naoInfo.NBas, naoInfo.NNAO  )
  File "/home/freeman/EzReson_v3.0_release/readNBOMat.py", line 224, in readNBOMat
    if spin <= 1: # spin-restricted
UnboundLocalError: local variable 'spin' referenced before assignment
```

请问是怎么回事呢？

**Comment by yangwangmadrid** [comment]
目前好像只支持pi共轭体系。不知是不是这个原因？首先，LMO的job是否正确结束？

**Comment by FreemanTheMaverick** [comment]
> 目前好像只支持pi共轭体系。不知是不是这个原因？首先，LMO的job是否正确结束？

应该不是这个原因。我用三重态苯（限制在D6h结构）测试的，LMO任务没有正常结束。

**Comment by yangwangmadrid** [comment]
可以把文件打包发我邮箱。（最好用小基组再试一下，如果还是出错，把小基组文件打包发我，这样体积较小）

**Comment by FreemanTheMaverick** [comment]
> 可以把文件打包发我邮箱。（最好用小基组再试一下，如果还是出错，把小基组文件打包发我，这样体积较小）

已发送

**Comment by yangwangmadrid** [comment]
很可能是你的33文件格式有问题。只有数据，文件开头缺少标题等header汪洋On 14 Apr 2023, at 18:12, FreemanTheMaverick ***@***.***> wrote:﻿

可以把文件打包发我邮箱。（最好用小基组再试一下，如果还是出错，把小基组文件打包发我，这样体积较小）

已发送

**Comment by FreemanTheMaverick** [comment]
> 很可能是你的33文件格式有问题。只有数据，文件开头缺少标题等header汪洋On 14 Apr 2023, at 18:12, FreemanTheMaverick ***@***.***> wrote:﻿ 可以把文件打包发我邮箱。（最好用小基组再试一下，如果还是出错，把小基组文件打包发我，这样体积较小） 已发送 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

好奇怪。这是不是高斯自带nbo3的bug啊？闭壳层就没有这个问题。

**Comment by FreemanTheMaverick** [comment]
在33文件前加上header，LMO可以正常运行结束了，但是WFRT还是报错如下：
```
(base) freeman@freeman-IdeaPad-Gaming-3-15IHU6:~/chemjob/test/benzene$ ezreson benzene_wfrt.in
EzReson version 3.0 (May 2022)
  -- A program for resonance analysis of a DFT wave function
Written by Yang WANG (yangwang@yzu.edu.cn)
Copyright 2022 Yang Wang

Performing Wave Function based Resonance Theory (WFRT) calculations ...
The pi resonance system is automatically defined by the alpha and beta LMOs:
Alpha LMOs:
 19 20 21 22
Beta LMOs:
 19 20

Traceback (most recent call last):
  File "/home/freeman/EzReson_v3.0_release/ezreson.py", line 1483, in <module>
    p.huckel, p.clarstyle, p.atomsexcl, p.sciform )
  File "/home/freeman/EzReson_v3.0_release/ezreson.py", line 1034, in runJob_WFRT
    projcut, 'uni', rao_tag, flipraos )
  File "/home/freeman/EzReson_v3.0_release/wfrt.py", line 608, in wfrt
    moIx = np.array( moIx1 ) - 1 # Starting from 0
TypeError: unsupported operand type(s) for -: 'range' and 'int'
```
[benzene.zip](https://github.com/yangwangmadrid/EzReson/files/11238720/benzene.zip)

**Comment by yangwangmadrid** [comment]
目前只适合对Kekule结构进行分析（否则各种离子型共振结构会非常多）。所以需要加上关键词：Kekule = TRUE
